# SonarCloud properties for test coverage reporting
sonar.projectKey=Kevin-Renault_Openclassrooms-Projet-3
sonar.organization=kevin-renault
sonar.host.url=https://sonarcloud.io
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
