spring.application.name=excercice1

# Server Configuration
server.port=3001
app.base-url=http://localhost:3001

# File Upload Configuration
file.upload-dir=uploads/pictures
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.datasource.url=jdbc:mysql://localhost:3306/chatop_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=kevin
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000

# Logging
logging.level.com.openclassrooms.projet3.excercice1.config.LoggingFilter=INFO